rootProject.name = 'orchestration-api'
include 'client-registry-api'
include 'oidc-api'
include 'orchestration-shared'
include 'orchestration-shared-test'
include 'identity-shared'
include 'ipv-api'
include 'integration-tests'
include 'sis-api'
include 'doc-checking-app-api'
include 'orchestration-local-running'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
}
